[ds-heap] binary heap implementation
pathfinder177/clang pull request #4
Opened 2024-05-09 10:40 UTC by pathfinder177

* adding binary heap

2024-05-09 16:54 UTC, Yanpas requested changes, later dismissed
I suggest you to review the API behind the heap. Most of the times we use heap to get "the largest (smallest) element: e.g. the timers queue. In this sense the heap behaves like a queue with push, pop and peek operations

2024-05-09 16:54 UTC, Yanpas commented on heap.c
> +#include "node.h"
Do you need a node?

2024-05-21 11:25 UTC, pathfinder177 commented on heap.c
> +#include "node.h"
Deleted

2024-05-21 11:25 UTC, pathfinder177 commented
> I suggest you to review the API behind the heap. Most of the times we use heap to get "the largest (smallest) element: e.g. the timers queue. In this sense the heap behaves like a queue with push, pop and peek operations

Began to implement

2024-05-23 13:12 UTC, merged